"""Create all tables

Revision ID: 12c1ba00148d
Revises:
Create Date: 2025-11-09 10:43:02.372257

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "12c1ba00148d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column(
            "platform",
            sa.Enum("olx", "uybor", "telegram", name="platform"),
            nullable=False,
        ),
        sa.Column("is_broker", sa.Boolean(), nullable=False),
        sa.Column("url", sa.VARCHAR(length=255), nullable=True),
        sa.Column("code", sa.VARCHAR(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_table(
        "posts",
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column(
            "type_of_property",
            sa.Enum("apartment", "commerce", "house", name="typeofproperty"),
            nullable=False,
        ),
        sa.Column(
            "type_of_service",
            sa.Enum("rent", "sale", name="typeofservice"),
            nullable=False,
        ),
        sa.Column("url", sa.TEXT(), nullable=False),
        sa.Column("title", sa.TEXT(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("olx", "uybor", "telegram", name="source"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("active", "verified", name="status"),
            nullable=False,
        ),
        sa.Column("external_id", sa.VARCHAR(length=20), nullable=False),
        sa.Column("phone_number", sa.VARCHAR(length=20), nullable=True),
        sa.Column("polygon_id", sa.BIGINT(), nullable=True),
        sa.Column("organization_id", sa.BIGINT(), nullable=False),
        sa.Column("is_broker", sa.Boolean(), nullable=False),
        sa.Column(
            "added_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_posts_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_posts")),
    )
    op.create_table(
        "post_rent_apartments",
        sa.Column("post_id", sa.CHAR(length=32), nullable=False),
        sa.Column("rooms", sa.SMALLINT(), nullable=True),
        sa.Column("floor", sa.SMALLINT(), nullable=True),
        sa.Column("total_floor", sa.SMALLINT(), nullable=True),
        sa.Column("total_area_sqm", sa.BIGINT(), nullable=True),
        sa.Column("total_price", sa.BIGINT(), nullable=True),
        sa.Column("is_new_building", sa.Boolean(), nullable=True),
        sa.Column("has_furniture", sa.Boolean(), nullable=True),
        sa.Column(
            "repair",
            sa.Enum(
                "designer",
                "euro",
                "average",
                "needs_repair",
                "rough_finish",
                "pre_finish",
                name="repair",
            ),
            nullable=True,
        ),
        sa.Column(
            "building_material",
            sa.Enum(
                "brick",
                "panel",
                "monolith",
                "block",
                "wood",
                name="buildingmaterial",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
            name=op.f("fk_post_rent_apartments_post_id_posts"),
        ),
        sa.PrimaryKeyConstraint(
            "post_id", name=op.f("pk_post_rent_apartments")
        ),
    )
    op.create_table(
        "post_rent_commerces",
        sa.Column("post_id", sa.CHAR(length=32), nullable=False),
        sa.Column("rooms", sa.SMALLINT(), nullable=True),
        sa.Column("floor", sa.SMALLINT(), nullable=True),
        sa.Column("total_floor", sa.SMALLINT(), nullable=True),
        sa.Column("total_area_sqm", sa.BIGINT(), nullable=True),
        sa.Column("land_area_sqm", sa.BIGINT(), nullable=True),
        sa.Column("total_price", sa.BIGINT(), nullable=True),
        sa.Column("has_furniture", sa.Boolean(), nullable=True),
        sa.Column(
            "repair",
            sa.Enum(
                "designer",
                "euro",
                "average",
                "needs_repair",
                "rough_finish",
                "pre_finish",
                name="repair",
            ),
            nullable=True,
        ),
        sa.Column(
            "purpose",
            sa.Enum(
                "магазины/бутики",
                "базы отдыха",
                "салоны",
                "помещения промышленного назначения",
                "рестораны/кафе/бары",
                "помещения свободного назначения",
                "офисы",
                "маф (малая архитектурная форма)",
                "склады",
                "часть здания",
                "отдельно стоящее здание",
                "другое",
                name="purpose",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
            name=op.f("fk_post_rent_commerces_post_id_posts"),
        ),
        sa.PrimaryKeyConstraint(
            "post_id", name=op.f("pk_post_rent_commerces")
        ),
    )
    op.create_table(
        "post_rent_houses",
        sa.Column("post_id", sa.CHAR(length=32), nullable=False),
        sa.Column("rooms", sa.SMALLINT(), nullable=True),
        sa.Column("total_floor", sa.SMALLINT(), nullable=True),
        sa.Column("total_area_sqm", sa.BIGINT(), nullable=True),
        sa.Column("land_area_sqm", sa.BIGINT(), nullable=True),
        sa.Column("total_price", sa.BIGINT(), nullable=True),
        sa.Column("has_furniture", sa.Boolean(), nullable=True),
        sa.Column(
            "building_material",
            sa.Enum(
                "brick",
                "panel",
                "monolith",
                "block",
                "wood",
                name="buildingmaterial",
            ),
            nullable=True,
        ),
        sa.Column(
            "repair",
            sa.Enum(
                "designer",
                "euro",
                "average",
                "needs_repair",
                "rough_finish",
                "pre_finish",
                name="repair",
            ),
            nullable=True,
        ),
        sa.Column(
            "house_type",
            sa.Enum(
                "дом",
                "флигель",
                "коттедж",
                "часть дома",
                "дача",
                "таунхаус",
                name="housetype",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
            name=op.f("fk_post_rent_houses_post_id_posts"),
        ),
        sa.PrimaryKeyConstraint("post_id", name=op.f("pk_post_rent_houses")),
    )
    op.create_table(
        "post_sale_apartments",
        sa.Column("post_id", sa.CHAR(length=32), nullable=False),
        sa.Column("rooms", sa.SMALLINT(), nullable=True),
        sa.Column("floor", sa.SMALLINT(), nullable=True),
        sa.Column("total_floor", sa.SMALLINT(), nullable=True),
        sa.Column("total_area_sqm", sa.BIGINT(), nullable=True),
        sa.Column("total_price", sa.BIGINT(), nullable=True),
        sa.Column("is_new_building", sa.Boolean(), nullable=True),
        sa.Column("has_furniture", sa.Boolean(), nullable=True),
        sa.Column(
            "repair",
            sa.Enum(
                "designer",
                "euro",
                "average",
                "needs_repair",
                "rough_finish",
                "pre_finish",
                name="repair",
            ),
            nullable=True,
        ),
        sa.Column(
            "building_material",
            sa.Enum(
                "brick",
                "panel",
                "monolith",
                "block",
                "wood",
                name="buildingmaterial",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
            name=op.f("fk_post_sale_apartments_post_id_posts"),
        ),
        sa.PrimaryKeyConstraint(
            "post_id", name=op.f("pk_post_sale_apartments")
        ),
    )
    op.create_table(
        "post_sale_commerces",
        sa.Column("post_id", sa.CHAR(length=32), nullable=False),
        sa.Column("rooms", sa.SMALLINT(), nullable=True),
        sa.Column("floor", sa.SMALLINT(), nullable=True),
        sa.Column("total_floor", sa.SMALLINT(), nullable=True),
        sa.Column("total_area_sqm", sa.BIGINT(), nullable=True),
        sa.Column("land_area_sqm", sa.BIGINT(), nullable=True),
        sa.Column("total_price", sa.BIGINT(), nullable=True),
        sa.Column("has_furniture", sa.Boolean(), nullable=True),
        sa.Column(
            "repair",
            sa.Enum(
                "designer",
                "euro",
                "average",
                "needs_repair",
                "rough_finish",
                "pre_finish",
                name="repair",
            ),
            nullable=True,
        ),
        sa.Column(
            "purpose",
            sa.Enum(
                "магазины/бутики",
                "базы отдыха",
                "салоны",
                "помещения промышленного назначения",
                "рестораны/кафе/бары",
                "помещения свободного назначения",
                "офисы",
                "маф (малая архитектурная форма)",
                "склады",
                "часть здания",
                "отдельно стоящее здание",
                "другое",
                name="purpose",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
            name=op.f("fk_post_sale_commerces_post_id_posts"),
        ),
        sa.PrimaryKeyConstraint(
            "post_id", name=op.f("pk_post_sale_commerces")
        ),
    )
    op.create_table(
        "post_sale_houses",
        sa.Column("post_id", sa.CHAR(length=32), nullable=False),
        sa.Column("rooms", sa.SMALLINT(), nullable=True),
        sa.Column("total_floor", sa.SMALLINT(), nullable=True),
        sa.Column("total_area_sqm", sa.BIGINT(), nullable=True),
        sa.Column("land_area_sqm", sa.BIGINT(), nullable=True),
        sa.Column("total_price", sa.BIGINT(), nullable=True),
        sa.Column("has_furniture", sa.Boolean(), nullable=True),
        sa.Column(
            "building_material",
            sa.Enum(
                "brick",
                "panel",
                "monolith",
                "block",
                "wood",
                name="buildingmaterial",
            ),
            nullable=True,
        ),
        sa.Column(
            "repair",
            sa.Enum(
                "designer",
                "euro",
                "average",
                "needs_repair",
                "rough_finish",
                "pre_finish",
                name="repair",
            ),
            nullable=True,
        ),
        sa.Column(
            "house_type",
            sa.Enum(
                "дом",
                "флигель",
                "коттедж",
                "часть дома",
                "дача",
                "таунхаус",
                name="housetype",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
            name=op.f("fk_post_sale_houses_post_id_posts"),
        ),
        sa.PrimaryKeyConstraint("post_id", name=op.f("pk_post_sale_houses")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("post_sale_houses")
    op.drop_table("post_sale_commerces")
    op.drop_table("post_sale_apartments")
    op.drop_table("post_rent_houses")
    op.drop_table("post_rent_commerces")
    op.drop_table("post_rent_apartments")
    op.drop_table("posts")
    op.drop_table("organizations")
    # ### end Alembic commands ###
